In [1]:
#step 1: import libraries needed
import pandas as pd

import numpy as np

import seaborn as sns

In [2]:
#step 2: load the "iris" dataset and store it as a data frame.

iris = sns.load_dataset('iris')

#show me it
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
#step 3: delete the species column (it is unnecessary and repetitive)
iris.drop(labels = 'species', axis = 1, inplace = True)
#1 is drop columns
#0 is drop rows

#show me it
iris.head()

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [4]:
#Step 4: Add two more columns to the iris data frame, "sepal_sum" and "petal_sum". 
#The "sepal_sum" is the sum of the values from the "sepal_length" and "sepal_width" columns. 
#On the other hand, The "petal_sum" is the sum of the values from the "petal_length" and "petal_width" columns.

#First sepal_sum
iris['sepal_sum'] = iris['sepal_length'] + iris['sepal_width']

#Second petal_Sum
iris['petal_sum'] = iris['petal_length'] + iris['petal_width']

#now THEORETICALLY that should work
#show me the MAGIC
iris.head()

   sepal_length  sepal_width  petal_length  petal_width  sepal_sum  petal_sum
0           5.1          3.5           1.4          0.2        8.6        1.6
1           4.9          3.0           1.4          0.2        7.9        1.6
2           4.7          3.2           1.3          0.2        7.9        1.5
3           4.6          3.1           1.5          0.2        7.7        1.7
4           5.0          3.6           1.4          0.2        8.6        1.6

I love when things work 👍

In [5]:
#step 5: Create a new data frame with the summary stats for the iris dataset. 
#For this summary, compute each column's mean, standard deviation, and minimum and maximum values.

mean = list(iris.mean())
stdev = list(iris.std())
min = list(iris.min())
max = list(iris.max())
summary_dict = {'mean':mean,'stdev':stdev,'min':min,'max':max}
index = ['sepal_length','sepal_width','petal_length','petal_width','sepal_sum', 'petal_sum']

summary_df = pd.DataFrame(data = summary_dict, index = index)
summary_df

                  mean     stdev  min   max
sepal_length  5.843333  0.828066  4.3   7.9
sepal_width   3.057333  0.435866  2.0   4.4
petal_length  3.758000  1.765298  1.0   6.9
petal_width   1.199333  0.762238  0.1   2.5
sepal_sum     8.900667  0.889272  6.8  11.7
petal_sum     4.957333  2.507689  1.2   9.2

SyntaxError: ignored